clean:
	rm -f ../process/preprocessed/*
	rm -f ../process/lifecycle/*

preprocess:
	python preprocess.py

run:
	python approach.py

test:
# 	make clean
# 	time python approach.py ./test2/ 3 preprocessed_2/
# 	make clean
# 	time python approach.py ./test10/ 3 preprocessed_10/
# 	make clean
# 	time python approach.py ./test30/ 3 preprocessed_30/
# 	make clean
# 	time python approach.py ./test60/ 3 preprocessed_60/
# 	make clean
# 	time python approach.py ./test90/ 3 preprocessed_90/